name: 'Technical Writer'
description: 'Technical Writer using OpenAI API'
inputs:
  openai_api_key:
    description: 'OpenAI API key'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.openai_api_key }}
