name: Technical Writer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tech-docs:
    name: Technical Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbut2/technical-writer@0d7d30de9157967639bf3d4ba6da6eca0915832c
