name: Technical Writer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tech-docs:
    name: Technical Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbut2/technical-writer@dev
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}

      - run: |
          pwd
          ls -lah
          git config --local --get remote.origin.url

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'update documentation'
          title: 'Documentation Update'
          body: 'Documentation Update'
          branch: 'docs/technical-writer'
          base: dev