name: Technical Writer

on:
  push:
    branches:
      - main

jobs:
  tech-docs:
    name: Technical Docs
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Tech Docs
        uses: dbut2/technical-writer@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}

      - name: Refresh git
        run: |
          git config --local --get remote.origin.url

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'update documentation'
          title: 'Documentation Update'
          body: 'Documentation Update'
          branch: 'docs/technical-writer'
          base: main